// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeAIExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeAIExtension.84cedc73-9f1b-4822-9a07-7a2927ba70fb";
        public const string Name = "CodeAIExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "k1sto";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
