// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeAIExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeAIExtension.f4bb9e46-e323-45eb-be73-331a48016999";
        public const string Name = "CodeAIExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Александр Лахов";
        public const string Tags = "";
    }
}
